name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['24', '25']
        electron: ['40', '41']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install Electron
        run: npm install --no-save electron@${{ matrix.electron }}

      - name: Run test:spark
        if: runner.os == 'Linux'
        run: xvfb-run npm run test:spark -- --verbose --reporter tap
      - name: Run test:node
        if: runner.os == 'Linux'
        run: xvfb-run npm run test:node -- --test-reporter=tap

      - name: Run test:spark
        if: runner.os != 'Linux'
        run: npm run test:spark -- --verbose --reporter tap
      - name: Run test:node
        if: runner.os != 'Linux'
        run: npm run test:node -- --test-reporter=tap

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - run: npm install

      - name: Run tests with coverage
        run: xvfb-run npm run coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: false
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - run: npm install
      - run: npm run lint
